service: user-activity-detection-socket

frameworkVersion: "2"

custom:
  prune:
    automatic: true
    number: 1

plugins:
  - serverless-pseudo-parameters
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  environment: ${file(serverless/env.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
      Resource:
        - { "Fn::GetAtt": ["DynamoDBTableUserConnectionStatus", "Arn"] }
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:provider.environment.USER_CONNECTION_STATUS_TABLE}/index/ByConnectionId

functions:
  connect:
    handler: src/handlers/connect.handler
    events:
      - websocket:
          route: $connect
  echo:
    handler: src/handlers/echo.handler
    events:
      - websocket:
          route: echo
  disconnect:
    handler: src/handlers/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  default:
    handler: src/handlers/default.handler
    events:
      - websocket:
          route: $default

resources:
  - ${file(serverless/resources/aws-dynamodb-user-connection-status-table.yml)}
